/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineBillingSystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public final class SearchBill extends javax.swing.JFrame {

   public Connection cn;
    public Statement st;
    public SearchBill() {
        initComponents();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/shrinidhi_stores?zeroDateTimeBehavior=convertToNull","root","");
           st=cn.createStatement();
           JOptionPane.showMessageDialog(null,"Connected");
           Headder();
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Print_Search = new javax.swing.JTextArea();
        C_Id_Bill = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Search_Bill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Print_Search.setColumns(20);
        Print_Search.setRows(5);
        jScrollPane1.setViewportView(Print_Search);

        C_Id_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_Id_BillActionPerformed(evt);
            }
        });

        jLabel5.setText("CUSTOMER_ID");

        Search_Bill.setText("Search");
        Search_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_Id_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_Bill)
                        .addGap(127, 127, 127)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C_Id_Bill)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(Search_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C_Id_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_Id_BillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_Id_BillActionPerformed

    private void Search_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BillActionPerformed
        /*BillingSystem bill=new BillingSystem();
        bill.setVisible(true);*/
        float qu;
        float tot;
        float g_total1;
        float g_total=0;
        Headder();
        try{
            String sqli;
            sqli="SELECT customer_id,item, quantity, cost FROM stocks WHERE customer_id="+C_Id_Bill.getText();
            ResultSet rs = st.executeQuery(sqli);
            //ResultSetMetaData rsmd = rs.getMetaData();

            String customer_id = "";
            String item = "";
            String quantity = "";
            String cost="";
            String total="";
            while(rs.next()){

                customer_id = rs.getString("customer_id");
                item  = rs.getString("item");
                quantity  = rs.getString("quantity");
                cost  = rs.getString("cost");
                qu=Float.parseFloat(quantity);
                tot=Float.parseFloat(cost);
                g_total1=qu*tot;
                g_total=g_total1+g_total;
                Print_Search.setText(Print_Search.getText()+"\n        "+item+"\t       "+quantity+"\t          "+g_total1);

            }
            Print_Search.setText(Print_Search.getText());
            Print_Search.setText(Print_Search.getText()+"\n****************************************************************\n\n TOTAL: "+g_total+"\n\nCustomer id :"+customer_id+"\n***************************************************************\n\n\tThank You Visit Again");
        }
        catch (SQLException e ) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_Search_BillActionPerformed
public void Headder(){
        Print_Search.setText("****************************************************************\n\n");
        Print_Search.setText(Print_Search.getText()+"                               SHRINIDHI STORES                      \n\n");
        Print_Search.setText(Print_Search.getText()+"****************************************************************");
        
        Date obj = new Date();
        String date=obj.toString();
        Print_Search.setText(Print_Search.getText()+"\n"+date+"\n");
        
        Print_Search.setText(Print_Search.getText()+"\n****************************************************************");
        Print_Search.setText(Print_Search.getText()+"\n           ITEM           QUANTITY(KG)        PRICE");
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SearchBill().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_Id_Bill;
    private javax.swing.JTextArea Print_Search;
    private javax.swing.JButton Search_Bill;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
